# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

parameters:
  - name: envs
    type: object
    default:
      - integration
      - webops

pool:
  vmImage: ubuntu-latest

steps:
  - task: TerraformInstaller@0
    displayName: 'Install Terraform 0.13.5'
    inputs:
      terraformVersion: '0.13.5'

  - task: AzureCLI@2
    displayName: 'Log into Azure CLI'
    inputs:
      azureSubscription: 'AzDevOps CSL Staging'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: 'az login'

  - ${{ each env in parameters.envs }}:
      - template: terraform-cmds.yaml
        parameters:
          env: ${{ env }}
